### ISSUE TITLE
Machine Learning for runtime improvement

### ISSUE THREAD

**Issue by JuliusKlodt** [DLR-SC/memilio#158]
Aim is to improve the runtime of a simulation.
=> Train a model with simulation data
==> Make predictions with machine learning model instead of a numerical simulation

**Comment by xsaschako** [comment]
@HenrZu did you work on this? maybe close/refer/or link this issue

**Comment by HenrZu** [comment]
Yes. The Issue here is simply described, but a lot of work. We already have a model for a simple application. However, extending it to multiple counties and integrating multiple NPI's still needs plenty of time.
I am currently waiting for a bigger pull request and after that I will restructure the whole machine learning/surrogate model again and open appropriate issues.

**Comment by AgathaSchmidt** [comment]
Closed in favour of #399
