### ISSUE TITLE
Add test set for population data

### ISSUE THREAD

**Issue by patricklnz** [DLR-SC/memilio#309]
In the tests for getCommuterData.py and getVaccinationData.py the population data is downloaded but the functionalities should be tested with test sets.

**Comment by HenrZu** [comment]
I already experienced this problem when working on Issue #281 with the `out_folder `default value.
Since we are using a fake file system for testing, it is a bit complicated to input data with the current structure.
I addressed a similar problem in Issue #293.

To facilitate this procedure, i started to restructure the function input, so the data path is always defined in the
main functions.
Therefore, it should be way easier to fix this issue when i'm done with the changes.
