### ISSUE TITLE
Output object for the ABM

### ISSUE THREAD

**Issue by xsaschako** [DLR-SC/memilio#424]
We should create a flexible output object for the results.

This object should handle the data saving, output to a txt file.

For now the data could be:
- Infection states per time step
- Infection states per time step per location type

related to #123

**Comment by jubicker** [comment]
Would it be possible to have the total number of people and the number of infected people  per hour and per location?

**Comment by xsaschako** [comment]
> Would it be possible to have the total number of people and the number of infected people per hour and per location?

What do you mean with the first thing? Just the total number of people? The other is certainly possible.

**Comment by DavidKerkmann** [comment]
I'd also like to have some clarification. Is it the number of total infected people or the number of newly infected people you are interested in? Also keep in mind that the time step is not always one hour. Do you want it per time step or always per one hour? If the latter is the case, then one might have to do some interpolation.

**Comment by jubicker** [comment]
Please remind @mknaranja to discuss this next week

**Comment by jubicker** [comment]
What we would need is for every location and for every time point: The number of agents per exposure time group where exposure time group means e.g. "not exposed", "exposed x hours ago", "exposed y hours ago" etc.
So for example for two time steps and two exposure time groups a table with the following columns:

- Location ID
- Timestep 1
- Number of agents in exposure time group 1
- Number of agents in exposure time group 2
- Timestep 2
- Number of agents in exposure time group 1
- Number of agents in exposure time group 2

Or the information on agent level meaning for two agents and two time steps a table with the following columns:

- Location ID
- Timestep 1
- Agent ID 1
- Time since exposure of agent 1
- Agent ID 2
- Time since exposure of agent 2
- Timestep 2
- Agent ID 1
- Time since exposure of agent 1
- Agent ID 2
- Time since exposure of agent 2

**Comment by jubicker** [comment]
The following output format ist need: A .txt file containing the columns:

- LocationID (should have the form xxyy where xx specifies the location type and yy the location index)
- Number of Output Timesteps
- Timestep 1 (t1)
- Number of Agents (in the location) in t1
- AgentID 1 (A1) in t1
- Time since Transmission to A1 in t1 (should be -1 if the agent is not infected)
- AgentID 2 in t1
-  Time since Transmission to A2 in t1
- ...
- Timestep 2 (t2)
- Number of Agents (in the location) in t2
- AgentID 1 in t2
- Time since Transmission to A1 in t2
- AgentID 2 in t2
-  Time since Transmission to A2 in t2
- ...
