### ISSUE TITLE
Error in compilation of abm_braunschweig for M1 machines with Xcode 15

### ISSUE THREAD

**Issue by khoanguyen-dev** [DLR-SC/memilio#809]
### Bug description

When we compile the abm_braunschweig.cpp, we encounter an error due to no template named 'unary_function' in namespace 'std' when using the `split.hpp` file. According to [Xcode 15 Release Notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes):

> unary_function and binary_function are no longer provided in C++17 and newer Standard modes. They can be re-enabled with _LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION.

### Version

Mac M1

### To reproduce

git clone [git@github.com](mailto:git@github.com):DLR-SC/memilio.git
cd memilio
mkdir build
cd build
cmake ../cpp

### Checklist

- [X] Attached labels, especially loc:: or model:: labels.
- [X] Linked to project

**Comment by khoanguyen-dev** [comment]
Replace

> boost::split(strings, string, boost::is_any_of(","));

with:

> size_t start = 0;
    size_t end   = string.find(",");
    while (end != std::string::npos) {
        strings.push_back(string.substr(start, end - start));
        start = end + 1;
        end   = string.find(",", start);
    }
    strings.push_back(string.substr(start, end));

**Comment by xsaschako** [comment]
Okay so this is the problem:

Current compilers may throw out unary function from the std library because it's deprecated.
apple clang did this, and i think some others too, e.g. gcc.

Our boost is somewhat older and newer boost libraries don't have that function. 
For now we should just compile with an cmake argument, so it doesnt use old code.
